import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const fallbackModelsPath = path.join(dir, "test", "tool", "fixtures", "models-api.json")

async function loadModelsData() {
  if (process.env.MODELS_DEV_API_JSON) return Bun.file(process.env.MODELS_DEV_API_JSON).text()
  try {
    return await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
  } catch (error) {
    if (!fs.existsSync(fallbackModelsPath)) throw error
    console.warn(`Falling back to local models fixture: ${fallbackModelsPath}`)
    return Bun.file(fallbackModelsPath).text()
  }
}

// Fetch and generate models.dev snapshot
const modelsData = await loadModelsData()
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.js"),
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
