export const ModelsFallbackResponse = {
  content: {
    opencode: {
      id: "opencode",
      name: "Octo AI",
      sortOrder: 1,
      env: ["OPENCODE_API_KEY"],
      npm: "@ai-sdk/openai-compatible",
      api: "http://octoai-llm.ucd.huawei.com/v1",
      models: [
        {
          id: "GLM-V5.1",
          name: "GLM V5.1",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          isExternal: false,
        },
        {
          id: "GLM-V5.2",
          name: "GLM V5.2",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          isExternal: false,
        },
        {
          id: "GLM V5.3",
          name: "GLM V5.3",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          isExternal: false,
        },
        {
          id: "DeepSeek-V4-Flash-0731",
          name: "DeepSeek-V4-Flash-0731",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          isExternal: false,
        },
        {
          id: "DeepSeek-V4-Flash",
          name: "DeepSeek-V4-Flash",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 16_000,
          },
        },
        {
          id: "Qwen-V3_6-27B-VL",
          name: "Qwen V3.6 27B VL",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          modalities: {
            input: ["text", "image"],
            output: ["text"],
          },
        },
      ],
    },
    bpit: {
      id: "bpit",
      name: "bpit",
      sortOrder: 2,
      env: ["OPENCODE_API_KEY"],
      npm: "@ai-sdk/openai-compatible",
      api: "http://aigateway.huawei.com/v1",
      models: [
        {
          id: "Qwen-V3_6-27B-VL",
          name: "Qwen V3.6 27B VL",
          attachment: true,
          reasoning: true,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          modalities: {
            input: ["text", "image"],
            output: ["text"],
          },
        },
        {
          id: "DeepSeek-V4-Flash",
          name: "DeepSeek V4 Flash",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
        },
        {
          id: "Qwen-V35-27B-VL",
          name: "Qwen V35 27B VL",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          modalities: {
            input: ["text", "image"],
            output: ["text"],
          },
        },
        {
          id: "GLM-V5",
          name: "GLM V5",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
        },
      ],
    },
    w3: {
      id: "w3",
      name: "Octo",
      sortOrder: 3,
      env: ["W3_KEY"],
      npm: "@ai-sdk/openai-compatible",
      api: "https://provide.hdesign.huawei.com/octo-llm-beta/v1",
      isExternal: false,
      models: [
        {
          id: "GLM-V5_1",
          name: "GLM V5.1",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          isExternal: false,
        },
        {
          id: "GLM-V5",
          name: "GLM V5",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          isExternal: false,
        },
        {
          id: "DeepSeek-V4-Flash",
          name: "DeepSeek V4 Flash",
          attachment: false,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          isExternal: false,
        },
        {
          id: "Qwen-V3_6-27B-VL",
          name: "Qwen V3.6 27B VL",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          modalities: {
            input: ["text", "image"],
            output: ["text"],
          },
          isExternal: false,
        },
        {
          id: "GLM-V5-WB",
          name: "GLM V5 WB",
          attachment: true,
          reasoning: false,
          temperature: true,
          tool_call: true,
          limit: {
            context: 128_000,
            output: 128_000,
          },
          isExternal: true,
        },
      ],
    },
  },
  success: true,
  errorCode: 200,
  errorMessage: null,
}
